### ISSUE TITLE
Add PBOs to Master branch

### ISSUE THREAD

**Issue by BnanaMan** [CreepPork/AchillesEnyoExpansion#17]
Hey I wanted to try out your addon, but I cant load the mod into arma since it isn't been packed into a pbo yet. I tried doing it myselfe just pboing all the folder in the addon folder, but when I launch the addon it cant find the ied sqf, and the moduls arent working i can put them down in zeus, but nothing happens

**Comment by CreepPork** [comment]
@BnanaMan Sure, I'll pack it when I will get home.

**Comment by BnanaMan** [comment]
@CreepPork thanks dude much apriciated

**Comment by CreepPork** [comment]
@BnanaMan You can pick the latest somewhat stable release from the Releases tab in GitHub.

**Comment by BnanaMan** [comment]
@CreepPork thanks for the effort, i still can only find the source code under releases though
https://github.com/CreepPork/AchillesEnyoExpansion/releases

**Comment by CreepPork** [comment]
@BnanaMan Then I forgot to pack it, sorry but you most likely will have to wait until tomorrow.

**Comment by BnanaMan** [comment]
@CreepPork ok no worries thanks again though

**Comment by CreepPork** [comment]
@BnanaMan For now I have a upload in Steam Workshop which is not to up-to-date with the code in the GitHub repo but is the second pre-release packed into PBOs and signed.

http://steamcommunity.com/sharedfiles/filedetails/?id=930110080

**Comment by CreepPork** [comment]
Added in 7d8eeae commit.
